import { and, asc, desc, eq, like, or } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { applications, conversations, messages, opportunities, pathwayChecklistItems, pathways, profiles, promptLibrary, savedOpportunities, InsertUser, users } from "../drizzle/schema";
import { ENV } from "./_core/env";
import { hasVerifiableSource, normalizeSourceUrl } from "../shared/sourceIntegrity";

let _db: ReturnType<typeof drizzle> | null = null;
export async function getDb() { if (!_db && process.env.DATABASE_URL) { try { _db = drizzle(process.env.DATABASE_URL); } catch (error) { console.warn("[Database] Failed to connect:", error); _db = null; } } return _db; }
export async function upsertUser(user: InsertUser): Promise<void> { if (!user.openId) throw new Error("User openId is required for upsert"); const db = await getDb(); if (!db) return; const values: InsertUser = { openId: user.openId }; const updateSet: Record<string, unknown> = {}; (["name", "email", "loginMethod"] as const).forEach(field => { if (user[field] !== undefined) { values[field] = user[field] ?? null; updateSet[field] = user[field] ?? null; } }); values.lastSignedIn = user.lastSignedIn ?? new Date(); updateSet.lastSignedIn = values.lastSignedIn; if (user.role) { values.role = user.role; updateSet.role = user.role; } else if (user.openId === ENV.ownerOpenId) { values.role = "admin"; updateSet.role = "admin"; } await db.insert(users).values(values).onDuplicateKeyUpdate({ set: updateSet }); }
export async function getUserByOpenId(openId: string) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(users).where(eq(users.openId, openId)).limit(1); return result[0]; }
export async function listOpportunities(search?: string, category?: "Study" | "Work" | "Skills" | "Business", province?: string) { const db = await getDb(); if (!db) return []; const filters = []; if (category) filters.push(eq(opportunities.category, category)); if (province) filters.push(eq(opportunities.province, province)); if (search) filters.push(or(like(opportunities.name, `%${search}%`), like(opportunities.organisation, `%${search}%`), like(opportunities.description, `%${search}%`), like(opportunities.traits, `%${search}%`))); const rows = await db.select().from(opportunities).where(filters.length ? and(...filters) : undefined).orderBy(desc(opportunities.sourceUpdatedAt)); return rows.filter(row => hasVerifiableSource(row.sourceUrl)); }
export async function listPromptLibrary() { const db = await getDb(); if (!db) return []; return db.select().from(promptLibrary).orderBy(asc(promptLibrary.category), asc(promptLibrary.displayOrder)); }
export async function createConversation(userId: number, title?: string) { const db = await getDb(); if (!db) return null; const result = await db.insert(conversations).values({ userId, title: title || "New career conversation" }); const rows = await db.select().from(conversations).where(eq(conversations.id, Number(result[0].insertId))).limit(1); return rows[0] ?? null; }
export async function listConversations(userId: number) { const db = await getDb(); if (!db) return []; return db.select().from(conversations).where(eq(conversations.userId, userId)).orderBy(desc(conversations.updatedAt)); }
export async function listMessages(userId: number, conversationId: number) { const db = await getDb(); if (!db) return []; const owned = await db.select().from(conversations).where(and(eq(conversations.id, conversationId), eq(conversations.userId, userId))).limit(1); if (!owned[0]) return []; return db.select().from(messages).where(eq(messages.conversationId, conversationId)).orderBy(asc(messages.createdAt)); }
export async function addMessage(userId: number, conversationId: number, sender: "user" | "assistant", message: string) { const db = await getDb(); if (!db) return null; const owned = await db.select().from(conversations).where(and(eq(conversations.id, conversationId), eq(conversations.userId, userId))).limit(1); if (!owned[0]) return null; const result = await db.insert(messages).values({ conversationId, sender, message }); await db.update(conversations).set({ updatedAt: new Date() }).where(eq(conversations.id, conversationId)); const rows = await db.select().from(messages).where(eq(messages.id, Number(result[0].insertId))).limit(1); return rows[0] ?? null; }
export async function toggleSavedOpportunity(userId: number, opportunityId: number | undefined, snapshotData: string) { const db = await getDb(); if (!db) return { saved: false, item: null }; let parsed: { sourceUrl?: string }; try { parsed = JSON.parse(snapshotData); } catch { throw new Error("Saved opportunity data must be valid JSON"); } if (!hasVerifiableSource(parsed.sourceUrl)) throw new Error("A verifiable HTTPS source URL is required"); const existing = await db.select().from(savedOpportunities).where(eq(savedOpportunities.userId, userId)); const match = existing.find(row => { if (opportunityId !== undefined && row.opportunityId === opportunityId) return true; try { const saved = JSON.parse(row.snapshotData || "{}"); return Boolean(parsed.sourceUrl && saved.sourceUrl === parsed.sourceUrl); } catch { return false; } }); if (match) { await db.delete(savedOpportunities).where(eq(savedOpportunities.id, match.id)); return { saved: false, item: match }; } const result = await db.insert(savedOpportunities).values({ userId, opportunityId, snapshotData }); const rows = await db.select().from(savedOpportunities).where(eq(savedOpportunities.id, Number(result[0].insertId))).limit(1); return { saved: true, item: rows[0] ?? null }; }
export async function listSavedOpportunities(userId: number) { const db = await getDb(); if (!db) return []; return db.select().from(savedOpportunities).where(eq(savedOpportunities.userId, userId)).orderBy(desc(savedOpportunities.createdAt)); }
export async function listApplications(userId: number) { const db = await getDb(); if (!db) return []; return db.select().from(applications).where(eq(applications.userId, userId)).orderBy(desc(applications.deadlineDate)); }
export async function createApplication(userId: number, input: Omit<typeof applications.$inferInsert, "userId">) { const db = await getDb(); if (!db) return null; const result = await db.insert(applications).values({ ...input, userId }); const id = Number(result[0].insertId); const rows = await db.select().from(applications).where(eq(applications.id, id)).limit(1); return rows[0] ?? null; }
export async function upsertProfile(userId: number, data: Omit<typeof profiles.$inferInsert, "userId">) { const db = await getDb(); if (!db) return null; const existing = await db.select().from(profiles).where(eq(profiles.userId, userId)).limit(1); if (existing[0]) { await db.update(profiles).set(data).where(eq(profiles.id, existing[0].id)); return { ...existing[0], ...data }; } const result = await db.insert(profiles).values({ ...data, userId }); return { id: Number(result[0].insertId), ...data, userId }; }
export async function listPathways(userId: number) { const db = await getDb(); if (!db) return []; return db.select().from(pathways).where(eq(pathways.userId, userId)).orderBy(desc(pathways.createdAt)); }
export async function listChecklistItems(userId: number, pathwayId: number) { const db = await getDb(); if (!db) return []; const owned = await db.select().from(pathways).where(and(eq(pathways.id, pathwayId), eq(pathways.userId, userId))).limit(1); if (!owned[0]) return []; return db.select().from(pathwayChecklistItems).where(eq(pathwayChecklistItems.pathwayId, pathwayId)).orderBy(asc(pathwayChecklistItems.sortOrder)); }
export async function updateChecklist(userId: number, itemId: number, isComplete: number) { const db = await getDb(); if (!db) return null; const rows = await db.select({ item: pathwayChecklistItems, pathway: pathways }).from(pathwayChecklistItems).innerJoin(pathways, eq(pathwayChecklistItems.pathwayId, pathways.id)).where(and(eq(pathwayChecklistItems.id, itemId), eq(pathways.userId, userId))).limit(1); if (!rows[0]) return null; await db.update(pathwayChecklistItems).set({ isComplete }).where(eq(pathwayChecklistItems.id, itemId)); return { ...rows[0].item, isComplete }; }

export async function updateApplication(userId: number, id: number, input: Partial<Omit<typeof applications.$inferInsert, "userId" | "id">>) { const db = await getDb(); if (!db) return null; await db.update(applications).set(input).where(and(eq(applications.id, id), eq(applications.userId, userId))); const rows = await db.select().from(applications).where(and(eq(applications.id, id), eq(applications.userId, userId))).limit(1); return rows[0] ?? null; }
export async function deleteApplication(userId: number, id: number) { const db = await getDb(); if (!db) return false; await db.delete(applications).where(and(eq(applications.id, id), eq(applications.userId, userId))); return true; }

export async function getProfile(userId: number) { const db = await getDb(); if (!db) return null; const rows = await db.select().from(profiles).where(eq(profiles.userId, userId)).limit(1); return rows[0] ?? null; }

export async function searchLiveOpportunities(query: string, category?: string, province?: string) { const searchQuery = [query || "South Africa youth career opportunities", category, province].filter(Boolean).join(" "); const apiKey = process.env.TAVILY_API_KEY; if (!apiKey) return { results: [], fallback: true, message: "Live search is not configured, so you are seeing curated opportunities." }; try { const response = await fetch("https://api.tavily.com/search", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ api_key: apiKey, query: searchQuery, search_depth: "basic", max_results: 8, include_answer: false }) }); if (!response.ok) return { results: [], fallback: true, message: "Live search is temporarily unavailable, so you are seeing curated opportunities." }; const payload = await response.json() as { results?: { title?: string; url?: string; content?: string }[] }; const results = (payload.results || []).map(item => ({ ...item, url: normalizeSourceUrl(item.url) })).filter(item => Boolean(item.url)).map(item => { const title = item.title || "Opportunity from live search"; const categoryGuess = /bursar|univers|college|course|study|scholar/i.test(title) ? "Study" : /job|intern|work|employment|learnership/i.test(title) ? "Work" : /business|enterprise|entrepreneur|fund/i.test(title) ? "Business" : "Skills"; return { id: undefined, name: title, organisation: new URL(item.url!).hostname.replace(/^www\./, ""), category: categoryGuess, description: (item.content || "Review the official source for current requirements.").slice(0, 260), traits: "Live result,verify source", province: province || "National", deadlineDate: null, sourceUrl: item.url!, sourceUpdatedAt: new Date(), source: "live" as const }; }); return { results, fallback: false, message: "From live search — verify before applying." }; } catch { return { results: [], fallback: true, message: "Live search timed out, so you are seeing curated opportunities." }; } }

export async function createPersonalisedPathway(userId: number, profile: string, message: string, assistantReply: string) { const db = await getDb(); if (!db) return null; const direction = message.trim().slice(0, 180) || "Explore a practical next step"; const result = await db.insert(pathways).values({ userId, goal: profile.slice(0, 500), currentSituation: message.slice(0, 500), recommendedDirection: direction, reasons: assistantReply.slice(0, 1200), nextSteps: "Review entry requirements; save one verified opportunity; identify one skill gap; prepare a first application draft", alternativeOptions: "Study, work, skills, or entrepreneurship routes can all be explored", immediateAction: "Save one verified opportunity and note its requirements", matchScore: 78 }); const pathwayId = Number(result[0].insertId); const items = ["Review the official entry requirements", "Save one verified opportunity that fits", "Identify one skill or document gap", "Prepare a first application draft"]; await db.insert(pathwayChecklistItems).values(items.map((text, index) => ({ pathwayId, text, isComplete: 0, isCustom: 0, sortOrder: index }))); const rows = await db.select().from(pathways).where(eq(pathways.id, pathwayId)).limit(1); return rows[0] ?? null; }

export async function adminListOpportunities() { const db = await getDb(); if (!db) return []; return db.select().from(opportunities).orderBy(desc(opportunities.sourceUpdatedAt)); }
export async function adminUpdateOpportunity(id: number, input: Partial<Omit<typeof opportunities.$inferInsert, "id">>) { const db = await getDb(); if (!db) return null; await db.update(opportunities).set({ ...input, sourceUpdatedAt: new Date() }).where(eq(opportunities.id, id)); const rows = await db.select().from(opportunities).where(eq(opportunities.id, id)).limit(1); return rows[0] ?? null; }
