import { and, desc, eq, like, or } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { applications, InsertUser, opportunities, profiles, users } from "../drizzle/schema";
import { ENV } from "./_core/env";

let _db: ReturnType<typeof drizzle> | null = null;
export async function getDb() { if (!_db && process.env.DATABASE_URL) { try { _db = drizzle(process.env.DATABASE_URL); } catch (error) { console.warn("[Database] Failed to connect:", error); _db = null; } } return _db; }
export async function upsertUser(user: InsertUser): Promise<void> { if (!user.openId) throw new Error("User openId is required for upsert"); const db = await getDb(); if (!db) return; const values: InsertUser = { openId: user.openId }; const updateSet: Record<string, unknown> = {}; (["name", "email", "loginMethod"] as const).forEach(field => { if (user[field] !== undefined) { values[field] = user[field] ?? null; updateSet[field] = user[field] ?? null; } }); values.lastSignedIn = user.lastSignedIn ?? new Date(); updateSet.lastSignedIn = values.lastSignedIn; if (user.role) { values.role = user.role; updateSet.role = user.role; } else if (user.openId === ENV.ownerOpenId) { values.role = "admin"; updateSet.role = "admin"; } await db.insert(users).values(values).onDuplicateKeyUpdate({ set: updateSet }); }
export async function getUserByOpenId(openId: string) { const db = await getDb(); if (!db) return undefined; const result = await db.select().from(users).where(eq(users.openId, openId)).limit(1); return result[0]; }
export async function listOpportunities(search?: string, category?: "Study" | "Work" | "Skills" | "Business") { const db = await getDb(); if (!db) return []; const filters = []; if (category) filters.push(eq(opportunities.category, category)); if (search) filters.push(or(like(opportunities.name, `%${search}%`), like(opportunities.organisation, `%${search}%`), like(opportunities.traits, `%${search}%`))); return db.select().from(opportunities).where(filters.length ? and(...filters) : undefined).orderBy(desc(opportunities.sourceUpdatedAt)); }
export async function listApplications(userId: number) { const db = await getDb(); if (!db) return []; return db.select().from(applications).where(eq(applications.userId, userId)).orderBy(desc(applications.deadlineDate)); }
export async function createApplication(userId: number, input: Omit<typeof applications.$inferInsert, "userId">) { const db = await getDb(); if (!db) return null; const result = await db.insert(applications).values({ ...input, userId }); const id = Number(result[0].insertId); const rows = await db.select().from(applications).where(eq(applications.id, id)).limit(1); return rows[0] ?? null; }
export async function upsertProfile(userId: number, data: Omit<typeof profiles.$inferInsert, "userId">) { const db = await getDb(); if (!db) return null; const existing = await db.select().from(profiles).where(eq(profiles.userId, userId)).limit(1); if (existing[0]) { await db.update(profiles).set(data).where(eq(profiles.id, existing[0].id)); return { ...existing[0], ...data }; } const result = await db.insert(profiles).values({ ...data, userId }); return { id: Number(result[0].insertId), ...data, userId }; }
